default_settings:
  retrain_models: False
  separator: "\t"
  dropout_column: 'Dropout'
  studentnumber_column: 'Studentnummer'
  save_method: 'xlsx'
  PROJ_ROOT: '.'
  DATA_DIR: './data'
  RAW_DATA_DIR: './data/raw'
  INTERIM_DATA_DIR: './data/interim'
  PROCESSED_DATA_DIR: './data/processed'
  EXTERNAL_DATA_DIR: './data/external'
  MODELS_DIR: './models'
  synth_data_dir_train: './data/raw/synth_data_train.csv'
  synth_data_dir_pred: './data/raw/synth_data_pred.csv'
  user_data_dir_train: './data/raw/user_data/train.csv'
  user_data_dir_pred: './data/raw/user_data/pred.csv'
  random_seed: 42
  rf_parameters:
    bootstrap: [true, false]
    max_depth: [2, 3, 4]
    max_features: [3, 4, 5]
    min_samples_leaf: [3, 4, 5]
    min_samples_split: [2, 3, 5]
    n_estimators: [100, 200, 300]
  alpha_range: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
  svm_parameters:
    C: [0.1, 1, 10, 100, 1000]
    gamma: [0.0001, 0.001, 0.01, 0.1, 1]
    kernel: ['rbf']

custom_settings:
  retrain_models: True
  separator: ','
  dropout_column: 'dropout'
  studentnumber_column: 'STUDENTNUMMER'
  save_method: 'xlsx'
  PROJ_ROOT: '.'
  DATA_DIR: './data'
  RAW_DATA_DIR: './data/raw'
  INTERIM_DATA_DIR: './data/interim'
  PROCESSED_DATA_DIR: './data/processed'
  EXTERNAL_DATA_DIR: './data/external'
  MODELS_DIR: './models'
  synth_data_dir_train: './data/raw/synth_data_train.csv'
  synth_data_dir_pred: './data/raw/synth_data_pred.csv'
  user_data_dir_train: './data/raw/user_data/train.csv'
  user_data_dir_pred: './data/raw/user_data/pred.csv'
  random_seed: 42
  rf_parameters:
    bootstrap: [true, false]
    max_depth: [2, 3, 4]
    max_features: [3, 4, 5]
    min_samples_leaf: [3, 4, 5]
    min_samples_split: [2, 3, 5]
    n_estimators: [100, 200, 300]
  lasso_parameters:
    alpha: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
  svm_parameters:
    C: [0.1, 1, 10, 100, 1000]
    gamma: [0.0001, 0.001, 0.01, 0.1, 1]
    kernel: ['rbf']
